sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - src # build src branch only
script:
  - chmod +x ./build.sh
  - ./build.sh
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  fqdn: www.breck-mckye.com
  on:
    branch: src
  local-dir: public
  